# Week 5 - Day 1: pandas Basics
**Goal:** Load SGX stock data into a DataFrame, explore it, and filter it.

pandas is THE data tool in Python. Think of a DataFrame as a spreadsheet/Excel table — rows and columns — but in code.

In [2]:
import pandas as pd

---
## Part 1: Load CSV into a DataFrame

New concepts:
- `import pandas as pd` — import pandas, call it "pd" for short
- `pd.read_csv("file.csv")` — reads a CSV file into a DataFrame
- A DataFrame is a table: rows (stocks) and columns (ticker, name, etc.)

In [ ]:
# TODO: Load the SGX stocks CSV
#   df = pd.read_csv("data/sgx_stocks.csv")
#   df
#
# In Jupyter, putting df on the last line displays it as a nice table
# (no need for print())

In [3]:
df = pd.read_csv("data/sgx_stocks.csv")

---
## Part 2: Explore the DataFrame

New concepts:
- `df.shape` — tuple of (rows, columns): (20, 7) means 20 stocks, 7 fields
- `df.columns` — list of column names
- `df.dtypes` — data type of each column (int64, float64, object = string)
- `df.head(n)` — first n rows (default 5)
- `df.tail(n)` — last n rows

In [4]:
# TODO: Check the shape (rows, columns)
#   df.shape
print(f"Shape: {df.shape}")

Shape: (20, 7)

In [5]:
# TODO: See all column names
#   df.columns
print(f"Columns: {list(df.columns)}")

Columns: ['ticker', 'name', 'sector', 'market_cap_m', 'price', 'dividend_yield', 'pe_ratio']

In [6]:
# TODO: Check data types of each column
#   df.dtypes
print(f"Data types: {(df.dtypes)}")

Data types: ticker             object
name               object
sector             object
market_cap_m        int64
price             float64
dividend_yield    float64
pe_ratio          float64
dtype: object

In [9]:
# TODO: Show first 5 rows
#   df.head()
print(f"First 5 rows: ({df.head(5)})")
df.head(5)

First 5 rows: (  ticker                name    sector  market_cap_m  price  dividend_yield  \
0    D05           DBS Group   Banking        108500  41.20             5.1
1    O39           OCBC Bank   Banking         65200  15.80             5.4
2    U11                 UOB   Banking         55800  34.50             4.8
3    Z74             Singtel   Telecom         42100   3.25             4.9
4    C6L  Singapore Airlines  Aviation         18900   6.85             3.2

   pe_ratio
0      10.2
1       9.8
2      10.5
3      18.3
4      15.7  )

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8
2,U11,UOB,Banking,55800,34.50,4.8,10.5
3,Z74,Singtel,Telecom,42100,3.25,4.9,18.3
4,C6L,Singapore Airlines,Aviation,18900,6.85,3.2,15.7

In [10]:
# TODO: Show last 3 rows
#   df.tail(3)
print(f"Last 3 rows: ({df.tail(3)})")
df.tail(3)

Last 3 rows: (   ticker                       name            sector  market_cap_m  price  \
17    BS6           YZJ Shipbuilding        Industrial          8200   2.15
18    H78              Hongkong Land       Real Estate         11200   5.30
19   M44U  Mapletree Logistics Trust  REIT - Logistics          7200   1.48

    dividend_yield  pe_ratio
17             4.5       8.9
18             4.7       7.5
19             6.5      13.2  )

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
17,BS6,YZJ Shipbuilding,Industrial,8200,2.15,4.5,8.9
18,H78,Hongkong Land,Real Estate,11200,5.30,4.7,7.5
19,M44U,Mapletree Logistics Trust,REIT - Logistics,7200,1.48,6.5,13.2

---
## Part 3: Select Columns

New concepts:
- `df["name"]` — one column → Series (like a list)
- `df[["name", "price"]]` — multiple columns → DataFrame (mini table)
- Note: single `[]` for one column, double `[[]]` for multiple

In [11]:
# TODO: Select just the stock names (single column → Series)
#   df["name"]
df["name"]

0                                  DBS Group
1                                  OCBC Bank
2                                        UOB
3                                    Singtel
4                         Singapore Airlines
5                      CapitaLand Investment
6                                Sea Limited
7                              Grab Holdings
8                   CapitaLand Ascendas REIT
9                    Frasers Logistics Trust
10    CapitaLand Integrated Commercial Trust
11       Mapletree Pan Asia Commercial Trust
12                Mapletree Industrial Trust
13                          Jardine Matheson
14                      Wilmar International
15                        Keppel Corporation
16                            ST Engineering
17                          YZJ Shipbuilding
18                             Hongkong Land
19                 Mapletree Logistics Trust
Name: name, dtype: object

In [12]:
# TODO: Select name, sector, and price (multiple columns → DataFrame)
#   df[["name", "sector", "price"]]
df[["name", "sector", "price"]]

                                      name             sector   price
0                                DBS Group            Banking   41.20
1                                OCBC Bank            Banking   15.80
2                                      UOB            Banking   34.50
3                                  Singtel            Telecom    3.25
4                       Singapore Airlines           Aviation    6.85
5                    CapitaLand Investment        Real Estate    3.12
6                              Sea Limited         Technology  125.40
7                            Grab Holdings         Technology    4.85
8                 CapitaLand Ascendas REIT  REIT - Industrial    2.78
9                  Frasers Logistics Trust  REIT - Industrial    1.22
10  CapitaLand Integrated Commercial Trust  REIT - Commercial    2.10
11     Mapletree Pan Asia Commercial Trust  REIT - Commercial    1.35
12              Mapletree Industrial Trust  REIT - Industrial    2.18
13                        Jardine Matheson       Conglomerate   48.70
14                    Wilmar International        Agriculture    3.42
15                      Keppel Corporation       Conglomerate    7.25
16                          ST Engineering         Industrial    4.58
17                        YZJ Shipbuilding         Industrial    2.15
18                           Hongkong Land        Real Estate    5.30
19               Mapletree Logistics Trust   REIT - Logistics    1.48

---
## Part 4: Filter Rows

New concepts:
- `df[df["sector"] == "Banking"]` — keep rows where sector equals "Banking"
- `df[df["dividend_yield"] > 5.0]` — keep rows where yield is above 5
- `df["sector"].str.contains("REIT")` — keep rows where sector contains "REIT"

How filtering works:
1. `df["sector"] == "Banking"` produces True/False for every row
2. `df[True/False list]` keeps only the True rows

In [14]:
# TODO: Filter — only banking stocks
#   banks = df[df["sector"] == "Banking"]
#   banks[["name", "price", "dividend_yield"]]
df[df["sector"] == "Banking"]

  ticker       name   sector  market_cap_m  price  dividend_yield  pe_ratio
0    D05  DBS Group  Banking        108500   41.2             5.1      10.2
1    O39  OCBC Bank  Banking         65200   15.8             5.4       9.8
2    U11        UOB  Banking         55800   34.5             4.8      10.5

In [15]:
# TODO: Filter — stocks with dividend yield above 5%
#   high_yield = df[df["dividend_yield"] > 5.0]
#   high_yield[["name", "sector", "dividend_yield"]]
df[df["dividend_yield"] > 5.0]

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8
8,A17U,CapitaLand Ascendas REIT,REIT - Industrial,12400,2.78,5.6,18.1
9,J69U,Frasers Logistics Trust,REIT - Industrial,4800,1.22,6.1,14.5
10,C38U,CapitaLand Integrated Commercial Trust,REIT - Commercial,14900,2.10,5.4,16.8
11,N2IU,Mapletree Pan Asia Commercial Trust,REIT - Commercial,8600,1.35,6.2,12.3
12,ME8U,Mapletree Industrial Trust,REIT - Industrial,6900,2.18,5.8,15.9
19,M44U,Mapletree Logistics Trust,REIT - Logistics,7200,1.48,6.5,13.2

In [17]:
# TODO: Filter — REITs only (sector contains "REIT")
#   reits = df[df["sector"].str.contains("REIT")]
#   reits[["name", "sector", "dividend_yield"]]
df[df["sector"].str.contains("REIT")]

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
8,A17U,CapitaLand Ascendas REIT,REIT - Industrial,12400,2.78,5.6,18.1
9,J69U,Frasers Logistics Trust,REIT - Industrial,4800,1.22,6.1,14.5
10,C38U,CapitaLand Integrated Commercial Trust,REIT - Commercial,14900,2.10,5.4,16.8
11,N2IU,Mapletree Pan Asia Commercial Trust,REIT - Commercial,8600,1.35,6.2,12.3
12,ME8U,Mapletree Industrial Trust,REIT - Industrial,6900,2.18,5.8,15.9
19,M44U,Mapletree Logistics Trust,REIT - Logistics,7200,1.48,6.5,13.2

---
## Part 5: Sort Values

New concepts:
- `df.sort_values("column")` — sort ascending (smallest first)
- `df.sort_values("column", ascending=False)` — sort descending (largest first)
- Chaining: `df.sort_values(...).head()` — sort, then take top 5

In [18]:
df.head(3)

  ticker       name   sector  market_cap_m  price  dividend_yield  pe_ratio
0    D05  DBS Group  Banking        108500   41.2             5.1      10.2
1    O39  OCBC Bank  Banking         65200   15.8             5.4       9.8
2    U11        UOB  Banking         55800   34.5             4.8      10.5

In [19]:
# TODO: Top 5 by market cap (largest first)
#   df.sort_values("market_cap_m", ascending=False)[["name", "sector", "market_cap_m"]].head()
df.sort_values("market_cap_m", ascending=False)[["name", "sector", "market_cap_m"]].head()

          name      sector  market_cap_m
0    DBS Group     Banking        108500
1    OCBC Bank     Banking         65200
2          UOB     Banking         55800
3      Singtel     Telecom         42100
6  Sea Limited  Technology         35600

In [ ]:
# TODO: Top 5 by dividend yield (highest first)
#   df.sort_values("dividend_yield", ascending=False)[["name", "sector", "dividend_yield"]].head()
df.sort_values("dividend_yield", ascending=False)[["name", "sector", "dividend_yield"]].head()

In [21]:
# TODO: Top 5 cheapest by PE ratio (lowest first, exclude 0)
#   has_pe = df[df["pe_ratio"] > 0]
#   has_pe.sort_values("pe_ratio")[["name", "sector", "pe_ratio"]].head()
has_pe = df[df["pe_ratio"] > 0]
has_pe.sort_values("pe_ratio")[["name", "sector", "pe_ratio"]].head()

                name       sector  pe_ratio
18     Hongkong Land  Real Estate       7.5
17  YZJ Shipbuilding   Industrial       8.9
1          OCBC Bank      Banking       9.8
0          DBS Group      Banking      10.2
2                UOB      Banking      10.5

---
## Part 6: Combine Filter + Sort + Select

Chain operations together to answer financial questions.

In [22]:
df.head(10)

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8
2,U11,UOB,Banking,55800,34.50,4.8,10.5
3,Z74,Singtel,Telecom,42100,3.25,4.9,18.3
4,C6L,Singapore Airlines,Aviation,18900,6.85,3.2,15.7
5,9CI,CapitaLand Investment,Real Estate,17800,3.12,3.8,22.4
6,SE,Sea Limited,Technology,35600,125.40,0.0,45.2
7,GRAB,Grab Holdings,Technology,14200,4.85,0.0,0.0
8,A17U,CapitaLand Ascendas REIT,REIT - Industrial,12400,2.78,5.6,18.1
9,J69U,Frasers Logistics Trust,REIT - Industrial,4800,1.22,6.1,14.5

In [23]:
# TODO: Question 1 — What are the top 3 highest-yielding REITs?
#   reits = df[df["sector"].str.contains("REIT")]
#   reits.sort_values("dividend_yield", ascending=False)[["name", "sector", "dividend_yield", "price"]].head(3)
reits = df[df["sector"].str.contains("REIT")]
reits.sort_values("dividend_yield", ascending=False)[["name", "sector", "dividend_yield", "price"]].head(3)

,name,sector,dividend_yield,price
19,Mapletree Logistics Trust,REIT - Logistics,6.5,1.48
11,Mapletree Pan Asia Commercial Trust,REIT - Commercial,6.2,1.35
9,Frasers Logistics Trust,REIT - Industrial,6.1,1.22

In [25]:
# TODO: Question 2 — Which banking stock has the lowest PE ratio?
#   banks = df[df["sector"] == "Banking"]
#   banks.sort_values("pe_ratio")[["name", "pe_ratio", "price"]].head(1)
banks = df[df["sector"] == "Banking"]
banks.sort_values("pe_ratio")[["name", "pe_ratio", "price"]].head(1)

        name  pe_ratio  price
1  OCBC Bank       9.8   15.8

In [28]:
# TODO: Question 3 — How many stocks have zero dividend?
#   no_div = df[df["dividend_yield"] == 0]
#   print(f"Stocks with no dividend: {len(no_div)}")
#   no_div[["name", "sector"]]
no_div = df[df["dividend_yield"] == 0]
print(f"Stocks with no dividend: {len(no_div)}")
no_div[["name", "sector"]]

Stocks with no dividend: 2

            name      sector
6    Sea Limited  Technology
7  Grab Holdings  Technology