# Week 5 - Day 2: pandas Analysis
**Goal:** Use groupby and aggregation to analyze SGX stocks by sector.

Yesterday you learned to load, filter, and sort data. Today you learn to
**group** data and compute **statistics** — the core of financial analysis.

In [1]:
import pandas as pd

df = pd.read_csv("data/sgx_stocks.csv")
df

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8
2,U11,UOB,Banking,55800,34.50,4.8,10.5
3,Z74,Singtel,Telecom,42100,3.25,4.9,18.3
4,C6L,Singapore Airlines,Aviation,18900,6.85,3.2,15.7
5,9CI,CapitaLand Investment,Real Estate,17800,3.12,3.8,22.4
6,SE,Sea Limited,Technology,35600,125.40,0.0,45.2
7,GRAB,Grab Holdings,Technology,14200,4.85,0.0,0.0
8,A17U,CapitaLand Ascendas REIT,REIT - Industrial,12400,2.78,5.6,18.1
9,J69U,Frasers Logistics Trust,REIT - Industrial,4800,1.22,6.1,14.5
10,C38U,CapitaLand Integrated Commercial Trust,REIT - Commercial,14900,2.10,5.4,16.8
11,N2IU,Mapletree Pan Asia Commercial Trust,REIT - Commercial,8600,1.35,6.2,12.3
12,ME8U,Mapletree Industrial Trust,REIT - Industrial,6900,2.18,5.8,15.9
13,J36,Jardine Matheson,Conglomerate,28500,48.70,3.5,12.1
14,F34,Wilmar International,Agriculture,21300,3.42,4.2,11.8
15,BN4,Keppel Corporation,Conglomerate,12800,7.25,3.9,14.2
16,S63,ST Engineering,Industrial,14500,4.58,3.4,22.8
17,BS6,YZJ Shipbuilding,Industrial,8200,2.15,4.5,8.9
18,H78,Hongkong Land,Real Estate,11200,5.30,4.7,7.5
19,M44U,Mapletree Logistics Trust,REIT - Logistics,7200,1.48,6.5,13.2

---
## Part 1: Quick Statistics with describe()

New concepts:
- `df.describe()` — summary stats for ALL numeric columns (count, mean, std, min, max, quartiles)
- `df["column"].mean()` — average of one column
- `df["column"].median()` — middle value
- `df["column"].sum()` — total
- `df["column"].std()` — standard deviation (how spread out)

In [2]:
# TODO: Get summary statistics for all numeric columns
#   df.describe()
df.describe()

        market_cap_m       price  dividend_yield   pe_ratio
count      20.000000   20.000000       20.000000  20.000000
mean    25470.000000   15.874000        4.350000  15.010000
std     25631.910621   29.402456        1.769775   8.800532
min      4800.000000    1.220000        0.000000   0.000000
25%     10550.000000    2.172500        3.725000  10.425000
50%     14700.000000    4.000000        4.750000  13.700000
75%     30275.000000    9.387500        5.450000  17.125000
max    108500.000000  125.400000        6.500000  45.200000

In [3]:
df["price"].mean()

np.float64(15.873999999999999)

In [4]:
df["price"].median()

4.0

In [5]:
df["price"].sum()

np.float64(317.47999999999996)

In [7]:
df["price"].std()

29.40245628836941

In [ ]:
# TODO: Calculate individual stats for dividend_yield
#   print(f"Average yield: {df['dividend_yield'].mean():.2f}%")
#   print(f"Median yield:  {df['dividend_yield'].median():.2f}%")
#   print(f"Total market cap: ${df['market_cap_m'].sum():,}M")

In [9]:
print(f"Average yield: {df["dividend_yield"].mean():.2f}%")
print(f"Median yield: {df["dividend_yield"].median():.2f}%")
print(f"Total market cap: ${df["market_cap_m"].sum():,}M")

Average yield: 4.35%
Median yield: 4.75%
Total market cap: $509,400M

---
## Part 2: groupby — Split Data by Category

New concepts:
- `df.groupby("sector")` — group rows that share the same sector
- Think of it like: "for each sector, do something"
- By itself, groupby does nothing visible — you need to add an aggregation (.mean(), .count(), etc.)

How it works:
1. **Split** — pandas divides rows into groups (Banking, Technology, etc.)
2. **Apply** — run a function on each group (mean, sum, count)
3. **Combine** — merge results into a new DataFrame

In [ ]:
# TODO: Count stocks per sector
#   df.groupby("sector")["name"].count()b

In [10]:
df.groupby("sector")["name"].count()

sector
Agriculture          1
Aviation             1
Banking              3
Conglomerate         2
Industrial           2
REIT - Commercial    2
REIT - Industrial    3
REIT - Logistics     1
Real Estate          2
Technology           2
Telecom              1
Name: name, dtype: int64

In [ ]:
# TODO: Average dividend yield per sector
#   df.groupby("sector")["dividend_yield"].mean()

In [12]:
df.groupby("sector")["dividend_yield"].mean()

sector
Agriculture          4.200000
Aviation             3.200000
Banking              5.100000
Conglomerate         3.700000
Industrial           3.950000
REIT - Commercial    5.800000
REIT - Industrial    5.833333
REIT - Logistics     6.500000
Real Estate          4.250000
Technology           0.000000
Telecom              4.900000
Name: dividend_yield, dtype: float64

In [ ]:
# TODO: Total market cap per sector (which sector is biggest?)
#   df.groupby("sector")["market_cap_m"].sum()

In [13]:
df.groupby("sector")["market_cap_m"].sum()

sector
Agriculture           21300
Aviation              18900
Banking              229500
Conglomerate          41300
Industrial            22700
REIT - Commercial     23500
REIT - Industrial     24100
REIT - Logistics       7200
Real Estate           29000
Technology            49800
Telecom               42100
Name: market_cap_m, dtype: int64

---
## Part 3: Sort groupby Results

New concept:
- Chain `.sort_values()` after groupby to rank the results
- `ascending=False` → largest first

In [ ]:
# TODO: Sectors ranked by average dividend yield (highest first)
#   df.groupby("sector")["dividend_yield"].mean().sort_values(ascending=False)

In [14]:
df.head(5)

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8
2,U11,UOB,Banking,55800,34.50,4.8,10.5
3,Z74,Singtel,Telecom,42100,3.25,4.9,18.3
4,C6L,Singapore Airlines,Aviation,18900,6.85,3.2,15.7

In [15]:
df.groupby("sector")["dividend_yield"].mean().sort_values(ascending=False)

sector
REIT - Logistics     6.500000
REIT - Industrial    5.833333
REIT - Commercial    5.800000
Banking              5.100000
Telecom              4.900000
Real Estate          4.250000
Agriculture          4.200000
Industrial           3.950000
Conglomerate         3.700000
Aviation             3.200000
Technology           0.000000
Name: dividend_yield, dtype: float64

In [ ]:
# TODO: Sectors ranked by total market cap (largest first)
#   df.groupby("sector")["market_cap_m"].sum().sort_values(ascending=False)

In [16]:
df.groupby("sector")["market_cap_m"].sum().sort_values(ascending=False)

sector
Banking              229500
Technology            49800
Telecom               42100
Conglomerate          41300
Real Estate           29000
REIT - Industrial     24100
REIT - Commercial     23500
Industrial            22700
Agriculture           21300
Aviation              18900
REIT - Logistics       7200
Name: market_cap_m, dtype: int64

---
## Part 4: agg() — Multiple Aggregations at Once

New concepts:
- `.agg()` lets you apply MULTIPLE functions to MULTIPLE columns in one call
- Pass a dictionary: `{"column": "function"}` or `{"column": ["func1", "func2"]}`
- Much more powerful than calling .mean(), .sum() one at a time

In [19]:
df

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8
2,U11,UOB,Banking,55800,34.50,4.8,10.5
3,Z74,Singtel,Telecom,42100,3.25,4.9,18.3
4,C6L,Singapore Airlines,Aviation,18900,6.85,3.2,15.7
5,9CI,CapitaLand Investment,Real Estate,17800,3.12,3.8,22.4
6,SE,Sea Limited,Technology,35600,125.40,0.0,45.2
7,GRAB,Grab Holdings,Technology,14200,4.85,0.0,0.0
8,A17U,CapitaLand Ascendas REIT,REIT - Industrial,12400,2.78,5.6,18.1
9,J69U,Frasers Logistics Trust,REIT - Industrial,4800,1.22,6.1,14.5
10,C38U,CapitaLand Integrated Commercial Trust,REIT - Commercial,14900,2.10,5.4,16.8
11,N2IU,Mapletree Pan Asia Commercial Trust,REIT - Commercial,8600,1.35,6.2,12.3
12,ME8U,Mapletree Industrial Trust,REIT - Industrial,6900,2.18,5.8,15.9
13,J36,Jardine Matheson,Conglomerate,28500,48.70,3.5,12.1
14,F34,Wilmar International,Agriculture,21300,3.42,4.2,11.8
15,BN4,Keppel Corporation,Conglomerate,12800,7.25,3.9,14.2
16,S63,ST Engineering,Industrial,14500,4.58,3.4,22.8
17,BS6,YZJ Shipbuilding,Industrial,8200,2.15,4.5,8.9
18,H78,Hongkong Land,Real Estate,11200,5.30,4.7,7.5
19,M44U,Mapletree Logistics Trust,REIT - Logistics,7200,1.48,6.5,13.2

In [18]:
sector_summary = df.groupby("sector").agg({
    "name": "count",
    "dividend_yield" : "mean",
    "market_cap_m": "sum",
    "pe_ratio" : "mean"
})
sector_summary

                   name  dividend_yield  market_cap_m   pe_ratio
sector
Agriculture           1        4.200000         21300  11.800000
Aviation              1        3.200000         18900  15.700000
Banking               3        5.100000        229500  10.166667
Conglomerate          2        3.700000         41300  13.150000
Industrial            2        3.950000         22700  15.850000
REIT - Commercial     2        5.800000         23500  14.550000
REIT - Industrial     3        5.833333         24100  16.166667
REIT - Logistics      1        6.500000          7200  13.200000
Real Estate           2        4.250000         29000  14.950000
Technology            2        0.000000         49800  22.600000
Telecom               1        4.900000         42100  18.300000

In [ ]:
# TODO: For each sector, get count, average yield, and total market cap
#   sector_summary = df.groupby("sector").agg({
#       "name": "count",
#       "dividend_yield": "mean",
#       "market_cap_m": "sum",
#       "pe_ratio": "mean"
#   })
#   sector_summary

In [21]:
sector_summary.columns = ["stock_count", "avg_yield", "total_cap_m", "avg_pe"]

In [23]:
sector_summary.sort_values("total_cap_m", ascending = False)

                   stock_count  avg_yield  total_cap_m     avg_pe
sector
Banking                      3   5.100000       229500  10.166667
Technology                   2   0.000000        49800  22.600000
Telecom                      1   4.900000        42100  18.300000
Conglomerate                 2   3.700000        41300  13.150000
Real Estate                  2   4.250000        29000  14.950000
REIT - Industrial            3   5.833333        24100  16.166667
REIT - Commercial            2   5.800000        23500  14.550000
Industrial                   2   3.950000        22700  15.850000
Agriculture                  1   4.200000        21300  11.800000
Aviation                     1   3.200000        18900  15.700000
REIT - Logistics             1   6.500000         7200  13.200000

In [ ]:
# TODO: Rename columns for clarity, then sort by market cap
#   sector_summary.columns = ["stock_count", "avg_yield", "total_cap_m", "avg_pe"]
#   sector_summary.sort_values("total_cap_m", ascending=False)

---
## Part 5: Computed Columns

New concepts:
- `df["new_col"] = expression` — create a new column from existing ones
- You can do math between columns: `df["a"] / df["b"]`
- `.round(2)` — round to 2 decimal places

In [ ]:
# TODO: Add a "yield_category" column based on dividend yield
#   High yield = above 5%, Medium = 3-5%, Low = below 3%
#
#   def classify_yield(y):
#       if y >= 5.0:
#           return "High"
#       elif y >= 3.0:
#           return "Medium"
#       else:
#           return "Low"
#
#   df["yield_category"] = df["dividend_yield"].apply(classify_yield)
#   df[["name", "dividend_yield", "yield_category"]]

In [24]:
def classify_yield(y):
    if y >= 5.0:
        return "High"
    elif y >= 3.0:
        return "Medium"
    else:
        return "Low"

In [28]:
df["yield_category"] = df["dividend_yield"].apply(classify_yield)

In [29]:
df[["name", "dividend_yield", "yield_category"]]

                                      name  dividend_yield yield_category
0                                DBS Group             5.1           High
1                                OCBC Bank             5.4           High
2                                      UOB             4.8         Medium
3                                  Singtel             4.9         Medium
4                       Singapore Airlines             3.2         Medium
5                    CapitaLand Investment             3.8         Medium
6                              Sea Limited             0.0            Low
7                            Grab Holdings             0.0            Low
8                 CapitaLand Ascendas REIT             5.6           High
9                  Frasers Logistics Trust             6.1           High
10  CapitaLand Integrated Commercial Trust             5.4           High
11     Mapletree Pan Asia Commercial Trust             6.2           High
12              Mapletree Industrial Trust             5.8           High
13                        Jardine Matheson             3.5         Medium
14                    Wilmar International             4.2         Medium
15                      Keppel Corporation             3.9         Medium
16                          ST Engineering             3.4         Medium
17                        YZJ Shipbuilding             4.5         Medium
18                           Hongkong Land             4.7         Medium
19               Mapletree Logistics Trust             6.5           High

In [ ]:
# TODO: Count stocks in each yield category
#   df.groupby("yield_category")["name"].count()

In [30]:
df.groupby("yield_category")["name"].count()

yield_category
High       8
Low        2
Medium    10
Name: name, dtype: int64

---
## Part 6: Financial Analysis Questions

Combine everything to answer real questions about the SGX market.

In [31]:
df

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio,yield_category
0,D05,DBS Group,Banking,108500,41.20,5.1,10.2,High
1,O39,OCBC Bank,Banking,65200,15.80,5.4,9.8,High
2,U11,UOB,Banking,55800,34.50,4.8,10.5,Medium
3,Z74,Singtel,Telecom,42100,3.25,4.9,18.3,Medium
4,C6L,Singapore Airlines,Aviation,18900,6.85,3.2,15.7,Medium
5,9CI,CapitaLand Investment,Real Estate,17800,3.12,3.8,22.4,Medium
6,SE,Sea Limited,Technology,35600,125.40,0.0,45.2,Low
7,GRAB,Grab Holdings,Technology,14200,4.85,0.0,0.0,Low
8,A17U,CapitaLand Ascendas REIT,REIT - Industrial,12400,2.78,5.6,18.1,High
9,J69U,Frasers Logistics Trust,REIT - Industrial,4800,1.22,6.1,14.5,High
10,C38U,CapitaLand Integrated Commercial Trust,REIT - Commercial,14900,2.10,5.4,16.8,High
11,N2IU,Mapletree Pan Asia Commercial Trust,REIT - Commercial,8600,1.35,6.2,12.3,High
12,ME8U,Mapletree Industrial Trust,REIT - Industrial,6900,2.18,5.8,15.9,High
13,J36,Jardine Matheson,Conglomerate,28500,48.70,3.5,12.1,Medium
14,F34,Wilmar International,Agriculture,21300,3.42,4.2,11.8,Medium
15,BN4,Keppel Corporation,Conglomerate,12800,7.25,3.9,14.2,Medium
16,S63,ST Engineering,Industrial,14500,4.58,3.4,22.8,Medium
17,BS6,YZJ Shipbuilding,Industrial,8200,2.15,4.5,8.9,Medium
18,H78,Hongkong Land,Real Estate,11200,5.30,4.7,7.5,Medium
19,M44U,Mapletree Logistics Trust,REIT - Logistics,7200,1.48,6.5,13.2,High

In [34]:
# TODO: Question 1 — Which REIT sub-sector (Industrial, Commercial, Logistics)
#   has the highest average yield?
reits = df[df["sector"].str.contains("REIT")]
reits.groupby("sector")["dividend_yield"].mean().sort_values(ascending=False)

sector
REIT - Logistics     6.500000
REIT - Industrial    5.833333
REIT - Commercial    5.800000
Name: dividend_yield, dtype: float64

In [ ]:
#   reits.groupby("sector")["dividend_yield"].mean().sort_values(ascending=False)

In [38]:
bank_reit = df[df["sector"].str.contains("Banking|REIT")].copy()

In [39]:
def simplify_sector(s):
    if "REIT" in s:
        return "REITS"
    return s

In [40]:
bank_reit["group"] = bank_reit["sector"].apply(simplify_sector)

In [ ]:
#       "name": "count",
#       "dividend_yield": "mean",
#       "pe_ratio": "mean",
#       "market_cap_m": "sum"

In [44]:
bank_reit.groupby("group").agg({
    "name": "count",
    "dividend_yield": "mean",
    "pe_ratio": "mean",
    "market_cap_m": "sum"
})

         name  dividend_yield   pe_ratio  market_cap_m
group
Banking     3        5.100000  10.166667        229500
REITS       6        5.933333  15.133333         54800

In [ ]:
# TODO: Question 2 — Compare banks vs REITs:
#   average yield, average PE, total market cap
#
#   bank_reit = df[df["sector"].str.contains("Banking|REIT")]
#   Compare using a simple groupby — but first, create a simpler label:
#
#   def simplify_sector(s):
#       if "REIT" in s:
#           return "REITs"
#       return s
#
#   bank_reit["group"] = bank_reit["sector"].apply(simplify_sector)
#   bank_reit.groupby("group").agg({
#       "name": "count",
#       "dividend_yield": "mean",
#       "pe_ratio": "mean",
#       "market_cap_m": "sum"
#   })

In [45]:
df.head(3)

,ticker,name,sector,market_cap_m,price,dividend_yield,pe_ratio,yield_category
0,D05,DBS Group,Banking,108500,41.2,5.1,10.2,High
1,O39,OCBC Bank,Banking,65200,15.8,5.4,9.8,High
2,U11,UOB,Banking,55800,34.5,4.8,10.5,Medium

In [49]:
sector_caps = df.groupby("sector")["market_cap_m"].sum()

In [50]:
total = df["market_cap_m"].sum()

In [51]:
pct = (sector_caps/total * 100).round(1)
pct.sort_values(ascending=False)

sector
Banking              45.1
Technology            9.8
Telecom               8.3
Conglomerate          8.1
Real Estate           5.7
REIT - Industrial     4.7
REIT - Commercial     4.6
Industrial            4.5
Agriculture           4.2
Aviation              3.7
REIT - Logistics      1.4
Name: market_cap_m, dtype: float64

In [ ]:
# TODO: Question 3 — What percentage of total market cap does each sector hold?
#
#   sector_caps = df.groupby("sector")["market_cap_m"].sum()
#   total = df["market_cap_m"].sum()
#   pct = (sector_caps / total * 100).round(1)
#   pct.sort_values(ascending=False)

In [ ]:
#   reits = df[df["sector"].str.contains("REIT")]
#   reits.groupby("sector")["dividend_yield"].mean().sort_values(ascending=False)